## Deliverable 3. Create a Travel Itinerary Map.

In [14]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [15]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("WeatherPy_vacation.csv")
vacation_df.head()

City_ID         City Country  Max Temp Current Description      Lat  \
0        5         Yuli      NG     89.01     overcast clouds   9.6989   
1       10  Keti Bandar      PK     78.19    scattered clouds  24.1447   
2       11       Atuona      PF     79.95       broken clouds  -9.8000   
3       14     Buchanan      LR     79.50     overcast clouds   5.8808   
4       16        Kapaa      US     78.78       broken clouds  22.0752   

        Lng                           Hotel Name  
0   10.2744                                  NaN  
1   67.4497               Haji laloo memon house  
2 -139.0333                          Villa Enata  
3  -10.0467                  Kamaneahn Hotel Inc  
4 -159.3190  Sheraton Kauai Coconut Beach Resort

In [16]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>

</dl>

"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [17]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [56]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"]=="Laguna"]
vacation_end = vacation_df.loc[vacation_df["City"]=="Laguna"]
vacation_stop1 = vacation_df.loc[vacation_df["City"]=="San Jose"]
vacation_stop2 = vacation_df.loc[vacation_df["City"]=="San Ramon"] 
vacation_stop3 = vacation_df.loc[vacation_df["City"]=="Half Moon Bay"] 

In [77]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[{"Lat","Lng"}].to_numpy()
end = vacation_end[{"Lat","Lng"}].to_numpy()
stop1 = vacation_stop1[{"Lat","Lng"}].to_numpy()
stop2 = vacation_stop2[{"Lat","Lng"}].to_numpy()
stop3 = vacation_stop3[{"Lat","Lng"}].to_numpy()

C:\Users\Heiliat\AppData\Local\Temp/ipykernel_18368/2053531910.py:2: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  start = vacation_start[{"Lat","Lng"}].to_numpy()
C:\Users\Heiliat\AppData\Local\Temp/ipykernel_18368/2053531910.py:3: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  end = vacation_end[{"Lat","Lng"}].to_numpy()
C:\Users\Heiliat\AppData\Local\Temp/ipykernel_18368/2053531910.py:4: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  stop1 = vacation_stop1[{"Lat","Lng"}].to_numpy()
C:\Users\Heiliat\AppData\Local\Temp/ipykernel_18368/2053531910.py:5: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  stop2 = vacation_stop2[{"Lat","Lng"}].to_numpy()
C:\Users\Heiliat\AppData\Local\Temp/ipykernel_18368/2053531910.py:6: Fut

In [73]:
start

array([[  38.421 , -121.4238]])

In [79]:
end

array([[  38.421 , -121.4238]])

In [80]:
stop1

array([[  37.3394, -121.895 ]])

In [89]:
stop2

array([[  37.7799, -121.978 ]])

In [81]:
stop3

array([[  37.4636, -122.4286]])

In [91]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
Start= (38.421, -121.42381)
End= (38.421, -121.42381)
Stop1=(37.3394, -121.895)
Stop2= (37.7799, -121.978)
Stop3=(37.4636, -122.4286)

geneva2zurich = gmaps.directions_layer(Start, End, waypoints=[Stop1,Stop2,Stop3],
                                      travel_mode='DRIVING')
fig.add_layer(geneva2zurich)
fig

#waypoints=[stop1,stop2,stop3]

Figure(layout=FigureLayout(height='420px'))

In [93]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_end, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID           City Country  Max Temp Current Description      Lat  \
0      567         Laguna      US     80.89           clear sky  38.4210   
1      567         Laguna      US     80.89           clear sky  38.4210   
2      106       San Jose      US     79.48           clear sky  37.3394   
3      655      San Ramon      US     80.82           clear sky  37.7799   
4      247  Half Moon Bay      US     79.54                mist  37.4636   

        Lng                                         Hotel Name  
0 -121.4238  Holiday Inn Express & Suites Elk Grove Central...  
1 -121.4238  Holiday Inn Express & Suites Elk Grove Central...  
2 -121.8950                                The Westin San Jose  
3 -121.9780                                 San Ramon Marriott  
4 -122.4286                    The Ritz-Carlton, Half Moon Bay

In [95]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>

</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [96]:
# 11a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))